language: node_js
node_js:
- '0.11'
services:
  - mongodb
cache:
  directories:
  - node_modules
deploy:
  - provider: heroku
    strategy: git
    api_key:
      secure: Xx6hQ9Em7jcIs7gaMRwi7tCwjNpgiPqR3ja58NeQj16iKZBAOwEaeetno0d51VXSpw7HyY+Njo0EiXo6DK1nDE0oyQZweUE0nRBLK8omlluRogrfH2YgDEIIT0cBXa9lGGpOW+ZO/vMfZ3NXnnhkORV73k4afloMVBuWOrX0NXo=
    app: asm-payments
    on:
      repo: asm-products/payments
  - provider: heroku
    strategy: git
    api_key:
      secure: opLvOBgeVvKYZQDctdWFadEbn0+xxT5FAflHgHqlQzGIR28CB95/i7UlsgvsqFEjxysBcl9TvkAcepV0g5Ca2xDqCPZFdmlRwaEOMGreNROWB/8Aq7IfPScrueRXk/kOvL/46QuggqnDf3itR75TH2q9oRAKDUHdXuXYcMWN5vo=
    app: asm-payments-sandbox
    on:
      repo: asm-products/payments
